// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl, config, request;

  request = require("request");

  config = require("./../config/config.json");

  MemberCtrl = (function() {
    function MemberCtrl() {}

    MemberCtrl.login = function(loginName, password, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/authUser?loginName=" + loginName + "&password=" + password;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    MemberCtrl.weixinLogin = function(openid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/authUser?openId=" + openid;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    MemberCtrl.bindWeChat = function(loginName, password, openid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/bindWeChat?loginName=" + loginName + "&password=" + password + "&openId=" + openid;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    MemberCtrl.unbindWeChat = function(openid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/unbindWeChat?openId=" + openid;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    MemberCtrl.getOption = function(id, openid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/getOption?id=" + id + "&openid=" + openid;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        var e, res;
        if (err) {
          return fn(err);
        } else {
          try {
            res = body != null ? JSON.parse(body) : {};
            if (res.error != null) {
              return fn(new Error(res.error));
            } else {
              return fn(null, res);
            }
          } catch (_error) {
            e = _error;
            return fn(e);
          }
        }
      });
    };

    MemberCtrl.setOption = function(id, company, name, tel, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/setOption?id=" + id + "&weixin_companyname=" + (encodeURIComponent(company)) + "&weixin_name=" + (encodeURIComponent(name)) + "&weixin_tel=" + tel;
      return request({
        url: url,
        timeout: 5000
      }, function(err, response, body) {
        if (err) {
          return fn(err);
        } else {
          return fn(null, body);
        }
      });
    };

    MemberCtrl.resetOption = function(id, openid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/resetOption?id=" + id + "&openid=" + openid;
      return request({
        url: url,
        timeout: 5000
      }, function(err, response, body) {
        if (err) {
          return fn(err);
        } else {
          return fn(null, body);
        }
      });
    };

    return MemberCtrl;

  })();

  module.exports = MemberCtrl;

}).call(this);
