// Generated by CoffeeScript 1.8.0
(function() {
  var ProductCtrl, config, request;

  request = require("request");

  config = require("./../config/config.json");

  ProductCtrl = (function() {
    function ProductCtrl() {}

    ProductCtrl.productList = function(fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/product/getlist?recommendedOnly=true&order=startDate";
      return request({
        url: url,
        timeout: 10000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    ProductCtrl.getSearchResult = function(startDate, cruiseArea, departureLocation, cruiseCompanyId, shipId, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/product/getSearchResult?time=" + (Date.now()) + "&startDate=" + startDate + "&cruiseArea=" + cruiseArea + "&departureLocation=" + (encodeURIComponent(departureLocation)) + "&cruiseCompanyId=" + cruiseCompanyId + "&shipId=" + shipId;
      console.log(url);
      return request({
        url: url,
        timeout: 10000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    ProductCtrl.productDetail = function(pid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/product/getdetail?productId=" + pid;
      return request({
        url: url,
        timeout: 10000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    ProductCtrl.productFee = function(pid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/product/getfees?productId=" + pid;
      return request({
        url: url,
        timeout: 10000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    ProductCtrl.shipInfo = function(shipId, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/product/getShipInfo?shipId=" + shipId;
      return request({
        url: url,
        timeout: 10000
      }, function(err, response, body) {
        var res;
        if (err) {
          return fn(err);
        } else {
          res = body != null ? JSON.parse(body) : {};
          if (res.error != null) {
            return fn(new Error(res.error));
          } else {
            return fn(null, res);
          }
        }
      });
    };

    ProductCtrl.sendMsg = function(name, tel, email, product, sendtoid, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/User/SendMessage?name=" + (encodeURIComponent(name)) + "&tel=" + tel + "&email=" + email + "&product=" + product + "&sendtoid=" + sendtoid;
      console.log(url);
      return request({
        url: url,
        timeout: 10000
      }, function(err, response, body) {
        if (err) {
          return fn(err);
        } else {
          return fn(null, body);
        }
      });
    };

    return ProductCtrl;

  })();

  module.exports = ProductCtrl;

}).call(this);
